2018-04-27 08:42:18,779 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 08:43:11,192 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 08:44:11,746 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 09:11:39,481 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 09:11:54,509 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 09:23:09,366 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 09:23:50,671 ERROR: Exception on /index [GET] [in /home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/inventory-container/flask-inventory/app/routes.py", line 21, in index
    return render_template('index.html', title='Home Page', posts=posts)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/app/templates/index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/pi/inventory-container/flask-inventory/app/templates/base.html", line 15, in top-level template code
    <a href="{{ url_for('print-label') }}">Print Label</a>
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/helpers.py", line 341, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 2053, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/helpers.py", line 330, in url_for
    force_external=external)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
BuildError: Could not build url for endpoint 'print-label'. Did you mean 'printLabel' instead?
2018-04-27 09:24:56,878 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 09:25:06,378 ERROR: Exception on /print-label [GET] [in /home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/inventory-container/flask-inventory/app/routes.py", line 72, in printLabel
    form = PrintLabelForm()
NameError: global name 'PrintLabelForm' is not defined
2018-04-27 09:25:41,387 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 09:25:57,368 ERROR: Exception on /printLabel [GET] [in /home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/inventory-container/flask-inventory/app/routes.py", line 72, in printLabel
    form = PrintLabelForm()
NameError: global name 'PrintLabelForm' is not defined
2018-04-27 09:26:20,559 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 09:26:24,311 ERROR: Exception on /printLabel [GET] [in /home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/inventory-container/flask-inventory/app/routes.py", line 89, in printLabel
    return render_template('printLabel.html', title='Print Labels', form=form)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/templating.py", line 58, in get_source
    return self._get_source_fast(environment, template)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/templating.py", line 86, in _get_source_fast
    raise TemplateNotFound(template)
TemplateNotFound: printLabel.html
2018-04-27 09:26:57,796 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
