2018-04-27 09:34:12,108 ERROR: Exception on /printLabel [POST] [in /home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/inventory-container/flask-inventory/app/routes.py", line 74, in printLabel
    item = Items.query.filter_by(ItemCode=itemCode.data).first()
NameError: global name 'itemCode' is not defined
2018-04-27 09:35:14,249 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 09:40:40,046 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 09:40:48,576 ERROR: Exception on /printLabel [POST] [in /home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/inventory-container/flask-inventory/app/routes.py", line 81, in printLabel
    flash('Printing Label ' + form.itemCode.data + '.' + item.ItemCodeDesc.data )
AttributeError: 'unicode' object has no attribute 'data'
2018-04-27 09:41:56,488 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 09:57:56,480 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 10:06:59,173 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 10:28:51,712 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 10:29:43,116 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 10:30:03,822 ERROR: Exception on /printLabel [POST] [in /home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/inventory-container/flask-inventory/app/routes.py", line 82, in printLabel
    sendPrintData(item)
NameError: global name 'sendPrintData' is not defined
2018-04-27 10:31:02,000 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 10:31:11,520 ERROR: Exception on /printLabel [POST] [in /home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/inventory-container/flask-inventory/app/routes.py", line 82, in printLabel
    pl.sendPrintData(item)
  File "/home/pi/inventory-container/flask-inventory/app/printlabel.py", line 54, in sendPrintData
    labeldata = createESCpLabel(result)
  File "/home/pi/inventory-container/flask-inventory/app/printlabel.py", line 61, in createESCpLabel
    code = str(item.ItemCode)
NameError: global name 'item' is not defined
2018-04-27 10:33:14,735 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 10:33:22,890 ERROR: Exception on /printLabel [POST] [in /home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/inventory-container/flask-inventory/app/routes.py", line 83, in printLabel
    pl.sendPrintData(item)
  File "/home/pi/inventory-container/flask-inventory/app/printlabel.py", line 54, in sendPrintData
    labeldata = createESCpLabel(result)
  File "/home/pi/inventory-container/flask-inventory/app/printlabel.py", line 61, in createESCpLabel
    code = str(item.ItemCode)
NameError: global name 'item' is not defined
2018-04-27 10:35:12,097 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
2018-04-27 10:35:24,641 ERROR: Exception on /printLabel [POST] [in /home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py:1753]
Traceback (most recent call last):
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/inventory-container/flask-inventory/venv/local/lib/python2.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/inventory-container/flask-inventory/app/routes.py", line 83, in printLabel
    pl.sendPrintData(item)
  File "/home/pi/inventory-container/flask-inventory/app/printlabel.py", line 54, in sendPrintData
    labeldata = createESCpLabel(result)
NameError: global name 'result' is not defined
2018-04-27 10:36:02,782 INFO: AMMK Inventory System startup [in /home/pi/inventory-container/flask-inventory/app/__init__.py:44]
